version: 2
updates:
  - package-ecosystem: "composer"
    allow:
      - dependency-type: all
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    versioning-strategy: "increase-if-necessary"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
